Update Flutter version parsing. Fixes #17 (#18)
* Update Flutter version parsing. Fixes #17
* Dependency versions bump

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -13,10 +13,10 @@ workflows:
     steps:
     - script:
         inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            stepman audit --step-yml ./step.yml
+          - content: |-
+              #!/bin/bash
+              set -ex
+              stepman audit --step-yml ./step.yml
   share-this-step:
     description: |-
       If this is the first time you try to share a Step you should
@@ -46,78 +46,78 @@ workflows:
     - BITRISE_STEP_ID: $BITRISE_STEP_ID
     - BITRISE_STEP_GIT_CLONE_URL: $BITRISE_STEP_GIT_CLONE_URL
     steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            bitrise share start -c "${MY_STEPLIB_REPO_FORK_GIT_URL}"
-            bitrise share create --stepid "${BITRISE_STEP_ID}" --tag "$(git describe --tags --exact-match)" --git "${BITRISE_STEP_GIT_CLONE_URL}"
-            bitrise share finish
+      - script:
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -ex
+                bitrise share start -c "${MY_STEPLIB_REPO_FORK_GIT_URL}"
+                bitrise share create --stepid "${BITRISE_STEP_ID}" --tag "$(git describe --tags --exact-match)" --git "${BITRISE_STEP_GIT_CLONE_URL}"
+                bitrise share finish
   test:
     after_run:
     - test-master
     - test-ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
     - test-multiple-versions
     steps:
-    - go-list: {}
-    - errcheck: {}
-    - go-test: {}
-    - golint: {}
-    - script:
-        title: Setup tests
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -e
+      - go-list: {}
+      - errcheck: {}
+      - go-test: {}
+      - golint: {}
+      - script:
+          title: Setup tests
+          inputs:
+            - content: |-
+                #!/usr/bin/env bash
+                # fail if any commands fails
+                set -e
 
-            if [[ "$OSTYPE" == darwin* ]]; then
-              FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build ios --simulator"
-            else
-              FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build apk"
-            fi
-            envman add --key FLUTTER_COMMANDS --value "$FLUTTER_COMMANDS"
+                if [[ "$OSTYPE" == darwin* ]]; then
+                  FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build ios --simulator"
+                else
+                  FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build apk"
+                fi
+                envman add --key FLUTTER_COMMANDS --value "$FLUTTER_COMMANDS"
   test-ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07:
     steps:
-    - change-workdir:
-        title: Switch working dir to test / _tmp_master dir
-        inputs:
-        - path: ./_tmp_ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
-        - is_create_path: true
-    - script:
-        title: Clone sample app
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            set -e
-            git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
-    - path::./:
-        title: Step Test
-        inputs:
-        - version: ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
-        - working_dir: flutter-app-example
-        - commands: $FLUTTER_COMMANDS
+      - change-workdir:
+          title: Switch working dir to test / _tmp_master dir
+          inputs:
+            - path: ./_tmp_ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
+            - is_create_path: true
+      - script:
+          title: Clone sample app
+          inputs:
+            - content: |-
+                #!/usr/bin/env bash
+                set -e
+                git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
+      - path::./:
+          title: Step Test
+          inputs:
+            - version: ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
+            - working_dir: flutter-app-example
+            - commands: $FLUTTER_COMMANDS
   test-master:
     steps:
-    - change-workdir:
-        title: Switch working dir to test / _tmp_master dir
-        inputs:
-        - path: ./_tmp_master
-        - is_create_path: true
-    - script:
-        title: Clone sample app
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            set -e
-            git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
-    - path::./:
-        title: Step Test
-        inputs:
-        - version: master
-        - working_dir: flutter-app-example
-        - commands: $FLUTTER_COMMANDS
+      - change-workdir:
+          title: Switch working dir to test / _tmp_master dir
+          inputs:
+            - path: ./_tmp_master
+            - is_create_path: true
+      - script:
+          title: Clone sample app
+          inputs:
+            - content: |-
+                #!/usr/bin/env bash
+                set -e
+                git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
+      - path::./:
+          title: Step Test
+          inputs:
+            - version: master
+            - working_dir: flutter-app-example
+            - commands: $FLUTTER_COMMANDS
   test-multiple-versions:
     steps:
       - change-workdir:
