Update build tools version retrieval fixes #33 (#34)
* setup macos build test

* Add CI build trigger to bitrise.yml

* Update go dependencies

* Update CI workflows
Refactor deprecated go code

* Change machine to osx-edge

* Update sdk build tools path finding mechanism

* Set linux build machine

* Update PATH in static code analysis step

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,22 +1,29 @@
 format_version: "11"
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: ""
+meta:
+  bitrise.io:
+    stack: linux-docker-android-22.04
+    machine_type_id: elite
 app:
   envs:
   - FLUTTER_COMMANDS: doctor --android-licenses|config --no-analytics|test
   - BITRISE_STEP_ID: flutter
   - BITRISE_STEP_GIT_CLONE_URL: https://github.com/DroidsOnRoids/bitrise-step-flutter.git
   - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
-
+trigger_map:
+- type: pull_request
+  workflow: test
+  pull_request_target_branch: '*'
 workflows:
   audit-this-step:
     steps:
     - script:
         inputs:
-          - content: |-
-              #!/bin/bash
-              set -ex
-              stepman audit --step-yml ./step.yml
+        - content: |-
+            #!/bin/bash
+            set -ex
+            stepman audit --step-yml ./step.yml
   share-this-step:
     description: |-
       If this is the first time you try to share a Step you should
@@ -46,101 +53,150 @@ workflows:
     - BITRISE_STEP_ID: $BITRISE_STEP_ID
     - BITRISE_STEP_GIT_CLONE_URL: $BITRISE_STEP_GIT_CLONE_URL
     steps:
-      - script:
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                bitrise share start -c "${MY_STEPLIB_REPO_FORK_GIT_URL}"
-                bitrise share create --stepid "${BITRISE_STEP_ID}" --tag "$(git describe --tags --exact-match)" --git "${BITRISE_STEP_GIT_CLONE_URL}"
-                bitrise share finish
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            bitrise share start -c "${MY_STEPLIB_REPO_FORK_GIT_URL}"
+            bitrise share create --stepid "${BITRISE_STEP_ID}" --tag "$(git describe --tags --exact-match)" --git "${BITRISE_STEP_GIT_CLONE_URL}"
+            bitrise share finish
   test:
     after_run:
     - test-master
     - test-ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
     - test-multiple-versions
     steps:
-      - go-list: {}
-      - errcheck: {}
-      - go-test: {}
-      - golint: {}
-      - script:
-          title: Setup tests
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                set -e
+    - git-clone@8: {}
+    - script:
+        title: Setup environment
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
 
-                if [[ "$OSTYPE" == darwin* ]]; then
-                  FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build ios --simulator"
-                else
-                  FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build apk"
-                fi
-                envman add --key FLUTTER_COMMANDS --value "$FLUTTER_COMMANDS"
+            rm -rf /opt/flutter/
+            go install github.com/kisielk/errcheck@latest
+    - go-list: {}
+    - script:
+        title: Static code analysis
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            
+            export PATH=$PATH:"$(go env GOPATH)/bin"
+            errcheck ./...
+            go vet
+    - go-test: {}
+    - script:
+        title: Setup tests
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+            if [[ "$OSTYPE" == darwin* ]]; then
+              FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build macos"
+            else
+              FLUTTER_COMMANDS="$FLUTTER_COMMANDS|build apk"
+            fi
+            envman add --key FLUTTER_COMMANDS --value "$FLUTTER_COMMANDS"
   test-ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07:
     steps:
-      - change-workdir:
-          title: Switch working dir to test / _tmp_master dir
-          inputs:
-            - path: ./_tmp_ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
-            - is_create_path: true
-      - script:
-          title: Clone sample app
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                set -e
-                git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
-      - path::./:
-          title: Step Test
-          inputs:
-            - version: ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
-            - working_dir: flutter-app-example
-            - commands: $FLUTTER_COMMANDS
+    - change-workdir:
+        title: Switch working dir to test / _tmp_master dir
+        inputs:
+        - path: ./_tmp_ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
+        - is_create_path: true
+    - script:
+        title: Clone sample app
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e
+            git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
+    - script:
+        title: Step test
+        inputs:
+          - content: |-
+              #!/usr/bin/env bash
+              set -e
+              cp ../bitrise.yml ../step.yml ../*.go ../go.mod .
+              go get
+              GOFLAGS=-buildvcs=false bitrise run step-test-3243
   test-master:
     steps:
-      - change-workdir:
-          title: Switch working dir to test / _tmp_master dir
-          inputs:
-            - path: ./_tmp_master
-            - is_create_path: true
-      - script:
-          title: Clone sample app
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                set -e
-                git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
-      - path::./:
-          title: Step Test
-          inputs:
-            - version: master
-            - working_dir: flutter-app-example
-            - commands: $FLUTTER_COMMANDS
+    - change-workdir:
+        title: Switch working dir to test / _tmp_master dir
+        inputs:
+        - path: ./_tmp_master
+        - is_create_path: true
+    - script:
+        title: Clone sample app
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e
+            git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
+    - script:
+        title: Step test
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e
+            echo $BITRISE_SOURCE_DIR
+            cp ../bitrise.yml ../step.yml ../*.go ../go.mod .
+            go get
+            GOFLAGS=-buildvcs=false bitrise run step-test-master
   test-multiple-versions:
     steps:
-      - change-workdir:
-          title: Switch working dir to test / _tmp_multiple dir
-          inputs:
-            - path: ./_tmp_multiple
-            - is_create_path: true
-      - script:
-          title: Clone sample app
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                set -e
-                git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
-      - path::./:
-          title: Step Test
-          inputs:
-            - version: ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
-            - working_dir: flutter-app-example
-            - commands: $FLUTTER_COMMANDS
+    - change-workdir:
+        title: Switch working dir to test / _tmp_multiple dir
+        inputs:
+        - path: ./_tmp_multiple
+        - is_create_path: true
+    - script:
+        title: Clone sample app
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -e
+            git clone https://github.com/DroidsOnRoidsPlayground/flutter-app-example.git
+    - script:
+        title: Step test
+        inputs:
+          - content: |-
+              #!/usr/bin/env bash
+              set -e
+              cp ../bitrise.yml ../step.yml ../*.go ../go.mod .
+              go get
+              GOFLAGS=-buildvcs=false bitrise run step-test-ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
+              GOFLAGS=-buildvcs=false bitrise run step-test-master
+  step-test-master:
+    steps:
       - path::./:
           title: Step Test
           inputs:
             - version: master
             - working_dir: flutter-app-example
             - commands: $FLUTTER_COMMANDS
+  step-test-ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07:
+    steps:
+      - path::./:
+          title: Step Test
+          inputs:
+          - version: ecf577ce5a7d8f3df1e320bc160d9f3eaf4a2e07
+          - working_dir: flutter-app-example
+          - commands: $FLUTTER_COMMANDS
+  step-test-3243:
+    steps:
+      - path::./:
+          title: Step Test
+          inputs:
+          - version: 3.24.3
+          - working_dir: flutter-app-example
+          - commands: $FLUTTER_COMMANDS
